### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by mustafa-barakat** [zhuowei/hipster.house#3]
Logging in results in 403 Forbidden

**Comment by zhuowei** [comment]
Looks like my API proxy was IP banned: let me fix it.

**Comment by zhuowei** [comment]
I've updated the proxy's IP address: try again in about half an hour?

**Comment by zhuowei** [comment]
This should be fixed.

**Comment by mustafa-barakat** [comment]
403 Again, This will keep happening as users continue to use it

**Comment by zhuowei** [comment]
Thanks. Might try to move this to a Cloud Function so it'd run from different IP addresses, or if that doesn't work, give up and provide an Electron/Cordova app download.

**Comment by zhuowei** [comment]
Moved to Cloud Functions. Please let me know if this works.

**Comment by zhuowei** [comment]
Closing: most auth requests are completing without 403 errors after move to Cloud Functions.
