### ISSUE TITLE
AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: no active status

### ISSUE THREAD

**Issue by tsecret** [zhuowei/hipster.house#5]
I am trying to build my React app using Agora v4.3.0, and when I call join call functions, I get the error above. I believe I am passing correct parameters to the functions, so I think the error might be on Agora side?

**Comment by zhuowei** [comment]
I have no idea, sorry: does the Agora sample code work for you if you create your own project?

**Comment by tsecret** [comment]
Yep, I am using Agora for another project and it works, but for some reasons, I am getting an error for clubhouse. 

As a reference, you can try to join this channel:
Agora APP: 938de3e8055e42b281bb8c6f69c21f78
channeID: M6GLLo2o
channel Token: 006938de3e8055e42b281bb8c6f69c21f78IAAE2x9g5Mc4jWqct8QW0Z1X4GLlU2OdihJIoFpEE/vmx4FUYzHhy9VsEAAEocwE5xQ1YAEAAQAAAAAA

**Comment by tsecret** [comment]
I have tried on a different PC, same error, could you give me an example of channel ID and token that works for you? Thanks!

**Comment by zhuowei** [comment]
I don't currently have a Clubhouse account with an invite, but you can probably use the Dev Console to grab the channel ID and token when joining a channel in hipster.house.

Honestly, I have no idea if hipster.house actually can connect to Agora with all the recent changes that Clubhouse added: you might want to use grishka's [Houseclub](https://github.com/grishka/Houseclub) Android app as a reference instead; that app is much more up to date.

**Comment by tsecret** [comment]
Got it, thanks!
